name: flutter_template
description: A custom default template for Flutter apps by Kasymbek "cos9" Tashbaev.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.0.0
  font_awesome_flutter: ^9.2.0
  form_builder_validators: ^7.0.0
  go_router: ^3.0.4
  google_fonts: ^2.3.1
  hooks_riverpod: ^1.0.3
  introduction_screen: ^2.1.0
  json_annotation: ^4.4.0
  permission_handler: ^8.2.5
  shared_preferences: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/images/
    - assets/fonts/
